apiVersion: apps/v1
kind: Deployment

metadata:
  name: php-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: php-app

  template:
    metadata:
      labels:
        app: php-app

    spec:
      containers:
      - name: php-container
        image: php-app
        imagePullPolicy: Never

        ports:
        - containerPort: 80
